<?php
// CHEMIN VERS IMAGES GALERIE
define('_GALERY_IMG_PATH_', 'uploads/cars/galerie_images/');
// CHEMIN VERS IMAGES ANNONCES VOITURES
define('_CARS_IMG_PATH_', 'uploads/cars/');
// CHEMIN VERS IMAGE PAR DEFAUT
define('_ASSETS_IMG_PATH_', 'assets/images/');
// LIMITE D'ANNONCES SUR LA PAGE D'ACCUEIL
define('_HOME_CARS_LIMIT_', 4);
// LIMITE D'ANNONCES SUR LA PAGE D'ACCUEIL
define('_HOME_REVIEWS_LIMIT_', 3);

define("_ADMIN_ITEM_PER_PAGE_", 10);
